# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            iworkoverti.me
tagline:          'The power of analysis'
description:      'Data visualization and long-winded observations of a student and data peasant'
url:              http://iworkoverti.me
baseurl:          /

author:
  name:           'Richard Brandt'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
